services:
  - docker
install:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - mkdir ${HOME}/.kube
  - echo "$KUBE_CONFIG" | base64 --decode > ${HOME}/.kube/config
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
env:
  ci: true
script:
  - kubectl get pods
  - docker build -t "$DOCKER_USERNAME"/keycloak .
  - docker images
  - docker push "$DOCKER_USERNAME"/keycloak
  - kubectl --context=\"cloud_okteto_com\" apply -f okteto/k8s.yml
